### ISSUE TITLE
Logging doesn't display usernames properly

### ISSUE THREAD

**Issue by fyyv** [plexusorg/Module-HTTPD#1]
This might just be due to the fact that I am visiting `localhost` from `localhost`, but the logging does not appear to populate with usernames correctly. Instead, `null` is shown in their place.

 ```
[<time> INFO]: [Plex HTTPD] null visited endpoint api/schematics/upload
[<time> INFO]: [Plex HTTPD] null visited endpoint api/schematics/download
```

I have only tested this on localhost, but it happens every time. There are no errors in console and my account has logged in to the game before. The IP address `127.0.0.1` is associated with my username and I can successfully upload schematics.

**Comment by Telesphoreo** [comment]
Not able to reproduce. This should show the IP of the person connecting.
