### ISSUE TITLE
Add commands route

### ISSUE THREAD

**Issue by Taahh** [plexusorg/Module-HTTPD#11]

**Comment by ncurran02** [comment]
Plan of action with commands - separate all commands by plugin
Tabled like
| Name (aliases) | Description | Usage | Permission |
|--------|--------|--------|--------|
| Command Name (Aliases) | Command Description | `/<command> <usage>` | command.perm.node |
| Command Name (Aliases) | Command Description | `/<command> <usage>` | command.perm.node |
| Command Name (Aliases) | Command Description | `/<command> <usage>` | command.perm.node |

@Taahh @Telesphoreo thoughts?

**Comment by Telesphoreo** [comment]
Looks good to me
