### ISSUE TITLE
IP address is not populated for offline players

### ISSUE THREAD

**Issue by fyyv** [plexusorg/Module-HTTPD#4]
The `ips` field on the `admins` endpoint is not populated for offline players. My database uses `sqlite`, and I have manually verified that an IP address exists for my account within `database.db`.

A consequence of this is that it is not possible to access any admin-only endpoints, or upload schematics, when not logged in to the server.

I would have assumed this were working as intended if it were not for the following recurring error in my logs. This appears any time I attempt to access admin-only endpoints while not in-game:
```
[<time> WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such function: json_search)
...
[<time> WARN]:        at Plex-1.0.2-SNAPSHOT.jar//dev.plex.storage.player.SQLPlayerData.getByIP(SQLPlayerData.java:176)
[<time> WARN]:        at Plex-1.0.2-SNAPSHOT.jar//dev.plex.cache.DataUtils.getPlayerByIP(DataUtils.java:100)
[<time> WARN]:        at dev.plex.request.impl.AdminsEndpoint.getAdmins(AdminsEndpoint.java:34)
...
[<time> WARN]:        at dev.plex.request.AbstractServlet.doGet(AbstractServlet.java:63)
...
```

**Comment by fyyv** [comment]
This could be a sign of bigger issues with the database. After I add a note to myself, an admin, it is not reflected in the `admins` endpoint even while I am online.

**Comment by Telesphoreo** [comment]
Certain parts of the HTTPD are restricted if you are not an admin. IP addresses will not show if you are not an admin. Can you post the full stacktrace of your error?

**Comment by Telesphoreo** [comment]
Resolved in the latest update of Plex
